#!/bin/bash
# Data gap fix commands generated by detect_gaps.py
# Generated: 2025-05-24 18:54:12

python run_daily.py --symbol AAPL --start 2025-05-01 --end 2025-05-19 --force
python run_daily.py --symbol MSFT --start 2025-05-01 --end 2025-05-19 --force
